#!/bin/bash

exist(){
	echo $(ps -p $1 | grep "$1" | wc -l)
}

#cherche les salons existants
tmp=$(ls -la /home | grep "^d..x..x..x" | cut -f4 -d" ")
for var in $tmp
do
	DIRECTORY=/home/$var/.chat
	if [ -d "$DIRECTORY" ] 
	then
		SERVEUR="$SERVEUR $var"
	fi
done

#Definition du nb de salons trouvés
NB_SERVEUR=$(echo $SERVEUR | wc -w)

#Creation d'un serveur si besoin
if [ $NB_SERVEUR -eq 0 ] || [[ $1 == "true" ]]
	then
	echo "creation d'un salon ..."
	echo ""
	echo "Attention : si vous quittez la conversation, le salon se fermera et deconnectera les autres membres !"
	echo ""
	mkdir -p /home/$(whoami)/.chat/
	chmod +x /home/$(whoami)
	chmod 777 /home/$(whoami)/.chat/
	touch /home/$(whoami)/.chat/chat
	chmod 777 /home/$(whoami)/.chat/chat
	SERVEUR=" $(whoami)"
	NB_SERVEUR=1
fi



#choix serveur
if [ $NB_SERVEUR -eq 1 ]
	then
	SERVEUR_CHOISIT=$(echo "$SERVEUR" | cut -f2 -d" ")
else
	echo "Plusieurs salons trouvés"
	echo ""
	echo "Choisissez un salon parmi les suivants :"
	echo ""

	let "ITERATE=$NB_SERVEUR+1"
	for i in `seq 2 $ITERATE`
	do
		(echo "$SERVEUR" | cut -f$i -d" ")
	done

	echo ""
	read -p "salon : " SERVEUR_CHOISIT
fi

PSEUDO=$(whoami)

DIR_SERVEUR=/home/$SERVEUR_CHOISIT/.chat

#creation du script d'ecriture
rm -fr $HOME/.bin/saisie.sh
touch $HOME/.bin/saisie.sh
chmod +x $HOME/.bin/saisie.sh

echo "while [ true ]" >> $HOME/.bin/saisie.sh
echo "do" >> $HOME/.bin/saisie.sh
echo "read -p \"votre message : \" line" >> $HOME/.bin/saisie.sh
echo "TIME=\$(date | cut -d\" \" -f5)" >> $HOME/.bin/saisie.sh
echo "echo \"\$1 - [\$TIME] : \$line\" >> \$2/chat" >> $HOME/.bin/saisie.sh
echo "clear" >> $HOME/.bin/saisie.sh
echo "done" >> $HOME/.bin/saisie.sh

#connection au serveur
xterm -hold -e "tail -f $DIR_SERVEUR/chat" &
PID_TAIL=$!

#Annonce de connexion
echo "********************* $PSEUDO is online  *********************" >> $DIR_SERVEUR/chat

#Lancement du script d'ecriture
xterm -hold -e "$HOME/.bin/saisie.sh $PSEUDO $DIR_SERVEUR" &
PID_SAISIE=$!


#Attente fermeture manuel d'un des terminaux
while [[ $(exist $PID_TAIL) == "1" ]] && [[ $(exist $PID_SAISIE) == "1" ]]
do
	sleep 0.002
done 	

#Si le processus "Tail" existe toujours
if [[ $(exist $PID_TAIL) == "1" ]]
	then

	#Fermer le processus "tail"
	kill -15 $PID_TAIL
fi

#Si le processus "Saisie" existe toujours
if [[ $(exist $PID_SAISIE) == "1" ]]
	then

	#Fermer le processus "saisie"
	kill -15 $PID_SAISIE
fi


#Annoce de deconnexion
echo "xxxxxxxxxxxxxxxxxxxxx $PSEUDO is offline xxxxxxxxxxxxxxxxxxxxx" >> $DIR_SERVEUR/chat

#Supprimer les fichiers temps
rm -fr $HOME/.bin/saisie.sh

#Fermeture du serveur (si local)
if [ $DIR_SERVEUR == "/home/$(whoami)/.chat" ]
	then
	rm -fr /home/$(whoami)/.chat/
	chmod g-x  /home/$(whoami)
	chmod o-x  /home/$(whoami)
fi